@startuml

node ControllerTester{
	component DummyOutput
	component InputModality
	component input_commands
	InputModality ..( publishCommands
	publishCommands .. input_commands

	component return_js_positions
	DummyOutput .. robotCommandCallback
	robotCommandCallback ).. return_js_positions

	component ResultChecker
	return_js_positions --* ResultChecker
	input_commands --* ResultChecker
}

interface command_js_topic
interface measured_js_topic
interface command_topic

InputModality -- command_topic
command_js_topic )-- DummyOutput
measured_js_topic -- DummyOutput

component Controller
command_topic )-- Controller
Controller --( measured_js_topic
Controller -- command_js_topic



@enduml
